import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/providers";
import Appbar from "./components/Appbar";
import SignInPanelWrapper from "./components/signInPanelWrapper";
import { ToastContainer } from "react-toastify";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Appbar>
            <SignInPanelWrapper />
          </Appbar>
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
